[project]
name = "airmouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gazi04", email = "gazmendhalili2016@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mediapipe>=1.0.1",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
]

[project.scripts]
airmouse = "airmouse:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
venvPath = "."
venv = ".venv"
